/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoloja.telas;

/**
 *
 * @author Usuário
 */
import java.sql.*;
import br.com.projetoloja.dal.ModuloConexao;
import javax.swing.JOptionPane;

public class TelaEditaEndereco extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    private String cpf_logado;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaEditaEndereco() {
        initComponents();
    }

    public TelaEditaEndereco(String cpf_logado) {
        this.cpf_logado = cpf_logado;
        System.out.println(cpf_logado);
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    private void buscarEnd() {
        String sql = "select * from tbendereco where id_endereco=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtIdEnderecoEdiEn.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                txtLograEdiEn.setText(rs.getString(2));
                txtEstadoEdiEn.setText(rs.getString(3));
                txtCidadeEdiEn.setText(rs.getString(4));
                txtBairroEdiEn.setText(rs.getString(5));
                txtNumeroEdiEn.setText(rs.getString(6));
                txtCepEdiEn.setText(rs.getString(7));
                txtComplementoEdiEn.setText(rs.getString(8));
            }else{
                JOptionPane.showMessageDialog(null, "Endereço não cadastrado");
                txtIdEnderecoEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtEstadoEdiEn.setText(null);
                txtCidadeEdiEn.setText(null);
                txtBairroEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtNumeroEdiEn.setText(null);
                txtCepEdiEn.setText(null);
                txtComplementoEdiEn.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
            
    }
    
    private void editarEnd() {
        String sql = "update tbendereco set logradouro=?, estado=?, cidade=?, bairro=?,\n"
                + "	numero=?, cep=?, complemento=? where id_endereco=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtLograEdiEn.getText());
            pst.setString(2, txtEstadoEdiEn.getText());
            pst.setString(3, txtCidadeEdiEn.getText());
            pst.setString(4, txtBairroEdiEn.getText());
            pst.setString(5, txtNumeroEdiEn.getText());
            pst.setString(6, txtCepEdiEn.getText());
            pst.setString(7, txtComplementoEdiEn.getText());
            pst.setString(8, txtIdEnderecoEdiEn.getText());

            if (txtLograEdiEn.getText().isEmpty() || txtEstadoEdiEn.getText().isEmpty()
                    || txtCidadeEdiEn.getText().isEmpty() || txtBairroEdiEn.getText().isEmpty()
                    || txtLograEdiEn.getText().isEmpty() || txtNumeroEdiEn.getText().isEmpty()
                    || txtCepEdiEn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            } else {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Campo(s) alterado(s) com sucesso!");
                txtLograEdiEn.setText(null);
                txtEstadoEdiEn.setText(null);
                txtCidadeEdiEn.setText(null);
                txtBairroEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtNumeroEdiEn.setText(null);
                txtCepEdiEn.setText(null);
                txtComplementoEdiEn.setText(null);
            }
            
            }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLograEdiEn = new javax.swing.JTextField();
        txtEstadoEdiEn = new javax.swing.JTextField();
        btnBuscEnd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCidadeEdiEn = new javax.swing.JTextField();
        txtBairroEdiEn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroEdiEn = new javax.swing.JTextField();
        txtCepEdiEn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtComplementoEdiEn = new javax.swing.JTextField();
        txtIdEnderecoEdiEn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnCadEnd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Endereço");
        setPreferredSize(new java.awt.Dimension(770, 500));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("*Logradouro:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("*Estado:");

        txtLograEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLograEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLograEdiEnActionPerformed(evt);
            }
        });

        txtEstadoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstadoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoEdiEnActionPerformed(evt);
            }
        });

        btnBuscEnd.setText("Buscar Endereço");
        btnBuscEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscEndActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("*Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("*Bairro: ");

        txtCidadeEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidadeEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeEdiEnActionPerformed(evt);
            }
        });

        txtBairroEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBairroEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroEdiEnActionPerformed(evt);
            }
        });

        jLabel9.setText("* Campos Obrigatórios");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("*Numero:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("*CEP:");

        txtNumeroEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEdiEnActionPerformed(evt);
            }
        });

        txtCepEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCepEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepEdiEnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Complemento:");

        txtComplementoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComplementoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoEdiEnActionPerformed(evt);
            }
        });

        txtIdEnderecoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdEnderecoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEnderecoEdiEnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Id Endereço:");

        btnCadEnd.setText("Confirmar Edições");
        btnCadEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtComplementoEdiEn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNumeroEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCepEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtLograEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEstadoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCidadeEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBairroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEnderecoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLograEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdEnderecoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstadoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCidadeEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBairroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtNumeroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCepEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtComplementoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 770, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLograEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLograEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLograEdiEnActionPerformed

    private void txtEstadoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoEdiEnActionPerformed

    private void btnBuscEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscEndActionPerformed
        // TODO add your handling code here:
        buscarEnd();
    }//GEN-LAST:event_btnBuscEndActionPerformed

    private void txtCidadeEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeEdiEnActionPerformed

    private void txtBairroEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroEdiEnActionPerformed

    private void txtNumeroEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEdiEnActionPerformed

    private void txtCepEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepEdiEnActionPerformed

    private void txtComplementoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoEdiEnActionPerformed

    private void txtIdEnderecoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEnderecoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEnderecoEdiEnActionPerformed

    private void btnCadEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEndActionPerformed
        // TODO add your handling code here:
        editarEnd();
    }//GEN-LAST:event_btnCadEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscEnd;
    private javax.swing.JButton btnCadEnd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairroEdiEn;
    private javax.swing.JTextField txtCepEdiEn;
    private javax.swing.JTextField txtCidadeEdiEn;
    private javax.swing.JTextField txtComplementoEdiEn;
    private javax.swing.JTextField txtEstadoEdiEn;
    private javax.swing.JTextField txtIdEnderecoEdiEn;
    private javax.swing.JTextField txtLograEdiEn;
    private javax.swing.JTextField txtNumeroEdiEn;
    // End of variables declaration//GEN-END:variables
}
