/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoloja.telas;

/**
 *
 * @author Usuário
 */
import java.sql.*;
import br.com.projetoloja.dal.ModuloConexao;
import javax.swing.JOptionPane;

public class TelaRemoveEndereco extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    private String cpf_logado;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaRemoveEndereco() {
        initComponents();
    }

    public TelaRemoveEndereco(String cpf_logado) {
        this.cpf_logado = cpf_logado;
        System.out.println(cpf_logado);
        initComponents();
        conexao = ModuloConexao.conector();
    }

   private void buscarEnd() {
        String sql = "select * from tbendereco where id_endereco=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtIdEnderecoEdiEn.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                txtLograEdiEn.setText(rs.getString(2));
                txtEstadoEdiEn.setText(rs.getString(3));
                txtCidadeEdiEn.setText(rs.getString(4));
                txtBairroEdiEn.setText(rs.getString(5));
                txtNumeroEdiEn.setText(rs.getString(6));
                txtCepEdiEn.setText(rs.getString(7));
                txtComplementoEdiEn.setText(rs.getString(8));
            }else{
                JOptionPane.showMessageDialog(null, "Endereço não cadastrado");
                txtIdEnderecoEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtEstadoEdiEn.setText(null);
                txtCidadeEdiEn.setText(null);
                txtBairroEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtNumeroEdiEn.setText(null);
                txtCepEdiEn.setText(null);
                txtComplementoEdiEn.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
            
    }

    private void removerEnd() {
        String sql = "delete from tbreside where id_endereco =?;";
        String sql2 = "delete from tbendereco where id_endereco =?;";
        
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover "
                + " este endereço?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtIdEnderecoEdiEnRem.getText());
                pst.executeUpdate();
                
                PreparedStatement pst2 = conexao.prepareStatement(sql2);
                pst2.setString(1, txtIdEnderecoEdiEnRem.getText());
                pst2.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Endereço removido com sucesso!");
                
                txtIdEnderecoEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtEstadoEdiEn.setText(null);
                txtCidadeEdiEn.setText(null);
                txtBairroEdiEn.setText(null);
                txtLograEdiEn.setText(null);
                txtNumeroEdiEn.setText(null);
                txtCepEdiEn.setText(null);
                txtComplementoEdiEn.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLograEdiEn = new javax.swing.JTextField();
        txtEstadoEdiEn = new javax.swing.JTextField();
        btnBuscEnd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCidadeEdiEn = new javax.swing.JTextField();
        txtBairroEdiEn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroEdiEn = new javax.swing.JTextField();
        txtCepEdiEn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtComplementoEdiEn = new javax.swing.JTextField();
        txtIdEnderecoEdiEnRem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnRemEnd = new javax.swing.JButton();
        txtIdEnderecoEdiEn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Endereço");
        setPreferredSize(new java.awt.Dimension(770, 500));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("*Logradouro:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("*Estado:");

        txtLograEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLograEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLograEdiEnActionPerformed(evt);
            }
        });

        txtEstadoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstadoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoEdiEnActionPerformed(evt);
            }
        });

        btnBuscEnd.setText("Buscar Endereço");
        btnBuscEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscEndActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("*Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("*Bairro: ");

        txtCidadeEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidadeEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeEdiEnActionPerformed(evt);
            }
        });

        txtBairroEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBairroEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroEdiEnActionPerformed(evt);
            }
        });

        jLabel9.setText("* Campos Obrigatórios");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("*Numero:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("*CEP:");

        txtNumeroEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEdiEnActionPerformed(evt);
            }
        });

        txtCepEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCepEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepEdiEnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Complemento:");

        txtComplementoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComplementoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoEdiEnActionPerformed(evt);
            }
        });

        txtIdEnderecoEdiEnRem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdEnderecoEdiEnRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEnderecoEdiEnRemActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Id Endereço:");

        btnRemEnd.setText("Remover Endereço");
        btnRemEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemEndActionPerformed(evt);
            }
        });

        txtIdEnderecoEdiEn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdEnderecoEdiEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEnderecoEdiEnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Id Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComplementoEdiEn)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumeroEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCepEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLograEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCidadeEdiEn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(txtIdEnderecoEdiEn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdEnderecoEdiEnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRemEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 105, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtLograEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstadoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtCidadeEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtIdEnderecoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtBairroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtNumeroEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCepEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtIdEnderecoEdiEnRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnRemEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtComplementoEdiEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        setBounds(0, 0, 770, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLograEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLograEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLograEdiEnActionPerformed

    private void txtEstadoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoEdiEnActionPerformed

    private void btnBuscEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscEndActionPerformed
        // TODO add your handling code here:
        buscarEnd();
    }//GEN-LAST:event_btnBuscEndActionPerformed

    private void txtCidadeEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeEdiEnActionPerformed

    private void txtBairroEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroEdiEnActionPerformed

    private void txtNumeroEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEdiEnActionPerformed

    private void txtCepEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepEdiEnActionPerformed

    private void txtComplementoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoEdiEnActionPerformed

    private void txtIdEnderecoEdiEnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEnderecoEdiEnRemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEnderecoEdiEnRemActionPerformed

    private void btnRemEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemEndActionPerformed
        // TODO add your handling code here:
        removerEnd();
    }//GEN-LAST:event_btnRemEndActionPerformed

    private void txtIdEnderecoEdiEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEnderecoEdiEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEnderecoEdiEnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscEnd;
    private javax.swing.JButton btnRemEnd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairroEdiEn;
    private javax.swing.JTextField txtCepEdiEn;
    private javax.swing.JTextField txtCidadeEdiEn;
    private javax.swing.JTextField txtComplementoEdiEn;
    private javax.swing.JTextField txtEstadoEdiEn;
    private javax.swing.JTextField txtIdEnderecoEdiEn;
    private javax.swing.JTextField txtIdEnderecoEdiEnRem;
    private javax.swing.JTextField txtLograEdiEn;
    private javax.swing.JTextField txtNumeroEdiEn;
    // End of variables declaration//GEN-END:variables
}
