/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoloja.telas;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuário
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private String cpf_logado;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    public TelaPrincipal(String cpf_logado) {
        this.cpf_logado = cpf_logado;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblCesta = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menVendas = new javax.swing.JMenu();
        menVendasReal = new javax.swing.JMenuItem();
        menVendasBusc = new javax.swing.JMenuItem();
        menProd = new javax.swing.JMenu();
        menProdBusc = new javax.swing.JMenuItem();
        menClien = new javax.swing.JMenu();
        menClienCad = new javax.swing.JMenuItem();
        menClienBusc = new javax.swing.JMenuItem();
        menClienEdi = new javax.swing.JMenuItem();
        menClienRem = new javax.swing.JMenuItem();
        menClienCadEnd = new javax.swing.JMenuItem();
        menClienEdiEnd = new javax.swing.JMenuItem();
        menClieRemEnd = new javax.swing.JMenuItem();
        menAdm = new javax.swing.JMenu();
        menAdmBusFunc = new javax.swing.JMenuItem();
        menAdmBuscForn = new javax.swing.JMenuItem();
        menAdmCadFunc = new javax.swing.JMenuItem();
        menAdmCadProd = new javax.swing.JMenuItem();
        MenAdmCadForn = new javax.swing.JMenuItem();
        menAdmCadAdm = new javax.swing.JMenuItem();
        menAdmCadCat = new javax.swing.JMenuItem();
        menAdmEdiFunc = new javax.swing.JMenuItem();
        menAdmEdiProd = new javax.swing.JMenuItem();
        menAdmEdiForn = new javax.swing.JMenuItem();
        menAdmEdiAdm = new javax.swing.JMenuItem();
        menAdmEdiCat = new javax.swing.JMenuItem();
        menAdmRemFunc = new javax.swing.JMenuItem();
        menAdmRemProd = new javax.swing.JMenuItem();
        menAdmRemAdm = new javax.swing.JMenuItem();
        menAdmRemCat = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menAjudaSobre = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BD Loja - Home");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(770, 500));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        lblCesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoloja/icones/cesta.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblData.setText("Data");

        menVendas.setText("Vendas");

        menVendasReal.setText("Realizar Venda");
        menVendas.add(menVendasReal);

        menVendasBusc.setText("Buscar Venda");
        menVendas.add(menVendasBusc);

        Menu.add(menVendas);

        menProd.setText("Produtos");

        menProdBusc.setText("Buscar Produto");
        menProd.add(menProdBusc);

        Menu.add(menProd);

        menClien.setText("Clientes");

        menClienCad.setText("Cadastrar Cliente");
        menClienCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienCadActionPerformed(evt);
            }
        });
        menClien.add(menClienCad);

        menClienBusc.setText("Buscar Cliente");
        menClienBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienBuscActionPerformed(evt);
            }
        });
        menClien.add(menClienBusc);

        menClienEdi.setText("Editar Cliente");
        menClienEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienEdiActionPerformed(evt);
            }
        });
        menClien.add(menClienEdi);

        menClienRem.setText("Remover Cliente");
        menClien.add(menClienRem);

        menClienCadEnd.setText("Cadastrar Endereço");
        menClienCadEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienCadEndActionPerformed(evt);
            }
        });
        menClien.add(menClienCadEnd);

        menClienEdiEnd.setText("Editar Endereço");
        menClienEdiEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienEdiEndActionPerformed(evt);
            }
        });
        menClien.add(menClienEdiEnd);

        menClieRemEnd.setText("Remover Endereço");
        menClieRemEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClieRemEndActionPerformed(evt);
            }
        });
        menClien.add(menClieRemEnd);

        Menu.add(menClien);

        menAdm.setText("Administração");
        menAdm.setEnabled(false);

        menAdmBusFunc.setText("Buscar Funcionário");
        menAdm.add(menAdmBusFunc);

        menAdmBuscForn.setText("Buscar Fornecedor");
        menAdm.add(menAdmBuscForn);

        menAdmCadFunc.setText("Cadastrar Funcionário");
        menAdmCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmCadFuncActionPerformed(evt);
            }
        });
        menAdm.add(menAdmCadFunc);

        menAdmCadProd.setText("Cadastrar Produto");
        menAdmCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmCadProdActionPerformed(evt);
            }
        });
        menAdm.add(menAdmCadProd);

        MenAdmCadForn.setText("Cadastrar Fornecedor");
        MenAdmCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdmCadFornActionPerformed(evt);
            }
        });
        menAdm.add(MenAdmCadForn);

        menAdmCadAdm.setText("Cadastrar Administrador");
        menAdmCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmCadAdmActionPerformed(evt);
            }
        });
        menAdm.add(menAdmCadAdm);

        menAdmCadCat.setText("Cadastrar Categoria");
        menAdmCadCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmCadCatActionPerformed(evt);
            }
        });
        menAdm.add(menAdmCadCat);

        menAdmEdiFunc.setText("Editar Funcionário");
        menAdm.add(menAdmEdiFunc);

        menAdmEdiProd.setText("Editar Produto");
        menAdm.add(menAdmEdiProd);

        menAdmEdiForn.setText("Editar Fornecedor");
        menAdm.add(menAdmEdiForn);

        menAdmEdiAdm.setText("Editar Administrador");
        menAdm.add(menAdmEdiAdm);

        menAdmEdiCat.setText("Editar Categoria");
        menAdm.add(menAdmEdiCat);

        menAdmRemFunc.setText("Remover Funcionário");
        menAdm.add(menAdmRemFunc);

        menAdmRemProd.setText("Remover Produto");
        menAdmRemProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdmRemProdActionPerformed(evt);
            }
        });
        menAdm.add(menAdmRemProd);

        menAdmRemAdm.setText("Remover Administrador");
        menAdm.add(menAdmRemAdm);

        menAdmRemCat.setText("Remover Categoria");
        menAdm.add(menAdmRemCat);

        Menu.add(menAdm);

        menAjuda.setText("Ajuda");

        menAjudaSobre.setText("Sobre");
        menAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjudaSobreActionPerformed(evt);
            }
        });
        menAjuda.add(menAjudaSobre);

        Menu.add(menAjuda);

        menOpc.setText("Opções");

        menOpcSair.setText("Sair");
        menOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcSairActionPerformed(evt);
            }
        });
        menOpc.add(menOpcSair);

        Menu.add(menOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCesta)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblData)
                        .addComponent(lblUsuario)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblUsuario)
                        .addGap(65, 65, 65)
                        .addComponent(lblData)
                        .addGap(77, 77, 77)
                        .addComponent(lblCesta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1018, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menClienCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienCadActionPerformed
        // TODO add your handling code here:
        TelaCadastraClien cadastraCli = new  TelaCadastraClien(cpf_logado);
        cadastraCli.setVisible(true);
        desktop.add(cadastraCli);
    }//GEN-LAST:event_menClienCadActionPerformed

    private void menAdmCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdmCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menAdmCadProdActionPerformed

    private void menAdmRemProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdmRemProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menAdmRemProdActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Atualizar a data do sistema ao inicializar o form na lblData
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcSairActionPerformed
        // Caixa de confirmação para sair do sistema.
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menOpcSairActionPerformed

    private void menAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjudaSobreActionPerformed
        // Executar a tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_menAjudaSobreActionPerformed

    private void menClienEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienEdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menClienEdiActionPerformed

    private void MenAdmCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdmCadFornActionPerformed
        // TODO add your handling code here:
        TelaCadastraForn fornecedor = new TelaCadastraForn(cpf_logado);
        fornecedor.setVisible(true);
        desktop.add(fornecedor);
    }//GEN-LAST:event_MenAdmCadFornActionPerformed

    private void menAdmCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdmCadFuncActionPerformed
        // Abrir o formulário no desktop do painel home
          TelaCadastraFuncio funcionario = new TelaCadastraFuncio(cpf_logado);
          funcionario.setVisible(true);
          desktop.add(funcionario);  
    }//GEN-LAST:event_menAdmCadFuncActionPerformed

    private void menClienBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienBuscActionPerformed
        // TODO add your handling code here:
        TelaConsultaCliente consultaCli = new TelaConsultaCliente();
        consultaCli.setVisible(true);
        desktop.add(consultaCli);
    }//GEN-LAST:event_menClienBuscActionPerformed

    private void menAdmCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdmCadAdmActionPerformed
        // TODO add your handling code here:
        TelaCadastraAdmin administrador = new TelaCadastraAdmin(cpf_logado);
        administrador.setVisible(true);
        desktop.add(administrador);
    }//GEN-LAST:event_menAdmCadAdmActionPerformed

    private void menAdmCadCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdmCadCatActionPerformed
        // TODO add your handling code here:
        TelaCadastraCatego categoria = new TelaCadastraCatego(cpf_logado);
        categoria.setVisible(true);
        desktop.add(categoria);
    }//GEN-LAST:event_menAdmCadCatActionPerformed

    private void menClienCadEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienCadEndActionPerformed
        // TODO add your handling code here:
        TelaCadastraEndereco endereco = new TelaCadastraEndereco(cpf_logado);
        endereco.setVisible(true);
        desktop.add(endereco);
    }//GEN-LAST:event_menClienCadEndActionPerformed

    private void menClienEdiEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienEdiEndActionPerformed
        // TODO add your handling code here:
        TelaEditaEndereco endereco = new TelaEditaEndereco(cpf_logado);
        endereco.setVisible(true);
        desktop.add(endereco);
    }//GEN-LAST:event_menClienEdiEndActionPerformed

    private void menClieRemEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClieRemEndActionPerformed
        // TODO add your handling code here:
        TelaRemoveEndereco endereco = new TelaRemoveEndereco(cpf_logado);
        endereco.setVisible(true);
        desktop.add(endereco);
    }//GEN-LAST:event_menClieRemEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenAdmCadForn;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel lblCesta;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenu menAdm;
    private javax.swing.JMenuItem menAdmBusFunc;
    private javax.swing.JMenuItem menAdmBuscForn;
    private javax.swing.JMenuItem menAdmCadAdm;
    private javax.swing.JMenuItem menAdmCadCat;
    private javax.swing.JMenuItem menAdmCadFunc;
    private javax.swing.JMenuItem menAdmCadProd;
    private javax.swing.JMenuItem menAdmEdiAdm;
    private javax.swing.JMenuItem menAdmEdiCat;
    private javax.swing.JMenuItem menAdmEdiForn;
    private javax.swing.JMenuItem menAdmEdiFunc;
    private javax.swing.JMenuItem menAdmEdiProd;
    private javax.swing.JMenuItem menAdmRemAdm;
    private javax.swing.JMenuItem menAdmRemCat;
    private javax.swing.JMenuItem menAdmRemFunc;
    private javax.swing.JMenuItem menAdmRemProd;
    private javax.swing.JMenu menAjuda;
    private javax.swing.JMenuItem menAjudaSobre;
    private javax.swing.JMenuItem menClieRemEnd;
    private javax.swing.JMenu menClien;
    private javax.swing.JMenuItem menClienBusc;
    private javax.swing.JMenuItem menClienCad;
    private javax.swing.JMenuItem menClienCadEnd;
    private javax.swing.JMenuItem menClienEdi;
    private javax.swing.JMenuItem menClienEdiEnd;
    private javax.swing.JMenuItem menClienRem;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcSair;
    private javax.swing.JMenu menProd;
    private javax.swing.JMenuItem menProdBusc;
    private javax.swing.JMenu menVendas;
    private javax.swing.JMenuItem menVendasBusc;
    private javax.swing.JMenuItem menVendasReal;
    // End of variables declaration//GEN-END:variables
}
